// ═══════════════════════════════════════════════════════════
//  DevForge — eslint.config.js
//  Flat config format (ESLint v9+)
// ═══════════════════════════════════════════════════════════

import js from "@eslint/js";

export default [
  {
    ignores: ["eslint.config.js", "debug_eslint.js"],
  },
  js.configs.recommended,
  {
    // Files to lint (all modular script files)
    files: ["*.js"],

    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script", // plain scripts, not ES modules
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        getComputedStyle: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        requestAnimationFrame: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Promise: "readonly",
        Set: "readonly",
        Map: "readonly",
        Blob: "readonly",
        FileReader: "readonly",

        // DevForge core curriculum data
        CURRICULUM: "readonly",

        // External CDN libraries
        LZString: "readonly",

        // Shared variables (writable across modules)
        currentLessonId: "writable",
        activeTab: "writable",
        lessonPaneOpen: "writable",
        consolePaneOpen: "writable",
        goalsPanelOpen: "writable",
        autorun: "writable",
        autorunTimer: "writable",
        fsPanelVisible: "writable",
        sidebarOpen: "writable",
        xp: "writable",
        streak: "writable",
        lastRunLesson: "writable",
        errorCount: "writable",
        revealedHints: "writable",
        consoleScrolledUp: "writable",
        CONSOLE_MAX_LINES: "readonly",
        consoleLineCount: "writable",
        isReadOnlyMode: "writable",
        doneSet: "writable",
        buffers: "writable",
        scrollPositions: "writable",
        activeLessonId: "writable",
        sessionStartTime: "writable",
        failedCheckLessons: "writable",
        activeModalEl: "writable",

        // Shared objects and namespace APIs
        CommandPalette: "readonly",
        Analytics: "readonly",

        // Shared functions (callable across modules)
        saveProgress: "readonly",
        scheduleSave: "readonly",
        loadProgress: "readonly",
        clearProgress: "readonly",
        getLocalDateString: "readonly",
        formatTimeSpent: "readonly",
        openAnalyticsModal: "readonly",
        closeAnalyticsModal: "readonly",
        resetAnalyticsConfirm: "readonly",
        renderAnalyticsData: "readonly",
        getModalFocusable: "readonly",
        openModal: "readonly",
        closeModal: "readonly",
        showResetModal: "readonly",
        hideResetModal: "readonly",
        showImportModal: "readonly",
        hideImportModal: "readonly",
        exportProgress: "readonly",
        triggerImport: "readonly",
        importProgress: "readonly",
        confirmImportProgress: "readonly",
        confirmReset: "readonly",
        copyAllCode: "readonly",
        changeFontSize: "readonly",
        toggleFsPanel: "readonly",
        openShortcutsModal: "readonly",
        closeShortcutsModal: "readonly",
        toggleShortcuts: "readonly",
        updateThemeButton: "readonly",
        applyTheme: "readonly",
        toggleTheme: "readonly",
        applySavedTheme: "readonly",
        showCompletion: "readonly",
        hideCompletion: "readonly",
        restartAll: "readonly",
        spawnConfetti: "readonly",
        showToast: "readonly",
        announce: "readonly",
        initResizer: "readonly",
        toggleSidebar: "readonly",
        toggleLessonPane: "readonly",
        editorUndo: "readonly",
        editorRedo: "readonly",
        applyEditorState: "readonly",
        onEditorInput: "readonly",
        pushUndoState: "readonly",
        flushUndoState: "readonly",
        seedUndoState: "readonly",
        commitUndoState: "readonly",
        updateLineNums: "readonly",
        syncScroll: "readonly",
        handleEditorKey: "readonly",
        highlight: "readonly",
        highlightHTML: "readonly",
        highlightCSS: "readonly",
        highlightJS: "readonly",
        escHtml: "readonly",
        escapeHtml: "readonly",
        toggleGoToLine: "readonly",
        showGoToLine: "readonly",
        hideGoToLine: "readonly",
        executeGoToLine: "readonly",
        getLesson: "readonly",
        getAllLessons: "readonly",
        getLessonIndex: "readonly",
        buildSidebar: "readonly",
        filterLessons: "readonly",
        clearSearch: "readonly",
        loadLesson: "readonly",
        saveCurrentBuffer: "readonly",
        renderLessonHints: "readonly",
        revealNextHint: "readonly",
        buildFileTabs: "readonly",
        switchTab: "readonly",
        loadTab: "readonly",
        updateNav: "readonly",
        navLesson: "readonly",
        escapeRegExp: "readonly",
        checkGoalRule: "readonly",
        checkAllGoalsMet: "readonly",
        validateGoals: "readonly",
        toggleGoalsPanel: "readonly",
        updateProgress: "readonly",
        toggleAutorun: "readonly",
        setPreviewSize: "readonly",
        generateSnapshot: "readonly",
        checkSnapshotOnLoad: "readonly",
        enterReadOnlyMode: "readonly",
        forkSnapshot: "readonly",
        runCode: "readonly",
        extractBody: "readonly",
        buildPreviewDoc: "readonly",
        clearConsoleUI: "readonly",
        addConsoleLog: "readonly",
        copyConsoleText: "readonly",
        toggleConsole: "readonly",
        filterConsole: "readonly",
        applyConsoleFilter: "readonly",
        clearConsoleFilter: "readonly",
      },
    },

    rules: {
      // ── Errors ──────────────────────────────────────────
      "no-undef": "error", // catch undefined variables
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-console": "off", // console.log is fine in this project
      "no-debugger": "error",

      // ── Best practices ───────────────────────────────────
      eqeqeq: ["error", "always"], // always use === not ==
      "no-var": "error", // use const/let only
      "prefer-const": "warn",
      "no-duplicate-case": "error",
      "no-dupe-else-if": "error",
      "no-empty": "error",
      "no-extra-semi": "error",
      "no-unreachable": "error",
      "no-lonely-if": "warn",

      // ── Style (warnings only, Prettier handles formatting) ─
      semi: ["warn", "always"],
      "no-trailing-spaces": "warn",
    },
  },
];
